// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// direct read flat json
CONF_mBool(enable_lazy_dynamic_flat_json, "true");

// enable flat complex type (/array/object/hyper type), diables for save storage
CONF_mBool(enable_json_flat_complex_type, "false");

// if disable flat complex type, check complex type rate in hyper-type column
CONF_mDouble(json_flat_complex_type_factor, "0.3");

// extract flat json column when row_num * null_factor > null_row_num
CONF_mDouble(json_flat_null_factor, "0.3");

// extract flat json column when row_num * sparsity_factor < hit_row_num
CONF_mDouble(json_flat_sparsity_factor, "0.3");

// the maximum number of extracted JSON sub-field
CONF_mInt32(json_flat_column_max, "100");

// for whitelist on flat json remain data, max set 1kb
CONF_mInt32(json_flat_remain_filter_max_bytes, "1024");

} // namespace starrocks::config
